; ============================================================================
; startup.s — BASSM Bare Metal Amiga Startup
; ============================================================================
;
; PURPOSE
;   This fragment is the first code in every generated BASSM program.
;   It is assembled by vasm (Motorola syntax, HUNK output) and runs as
;   an AmigaOS CLI executable. It:
;
;     1. Saves the current AmigaOS hardware state
;     2. Calls Forbid() — stops OS task switching
;     3. Disables all hardware interrupts and DMA
;     4. Installs our own Level-3 (VBlank) interrupt handler
;     5. Enables Copper + Bitplane + Blitter DMA
;     6. Enables the VBlank interrupt
;     7. Calls _main_program (generated by the BASSM codegen)
;     8. Restores all hardware state and AmigaOS ownership
;
; REGISTER CONVENTION (maintained throughout the entire generated program)
;   a5 = $DFF000  Custom chip registers base  (set at startup, kept forever)
;   a6 = ExecBase                             (only used during init/cleanup)
;   d0-d7, a0-a4 = scratch for generated code
;
; INTERFACE FOR CODEGEN
;   The generated code MUST define the label:   _main_program
;   Optionally it may set:                       _vblank_hook
;     (a longword holding the address of a subroutine called every VBlank)
;
; UTILITY SUBROUTINES (callable from generated code)
;   _WaitVBL        — stalls until the next vertical blank fires
;   _GetFrameCount  — returns current 50Hz frame counter in d0
;   _SetVBlankHook  — registers a callback for every VBlank
;
; TARGET
;   OCS/ECS Amiga (A500 / A2000 / A600), PAL, 68000
;   Kickstart 1.3 or later
;
; ASSEMBLE WITH
;   vasmm68k_mot -Fhunk -o program.exe generated.s
; ============================================================================


; ── Custom Chip Register Offsets (relative to $DFF000) ──────────────────────
; Read registers
DMACONR     EQU $002        ; DMA control (read)
INTENAR     EQU $01C        ; Interrupt enable (read)
INTREQR     EQU $01E        ; Interrupt request (read)

; Write registers
COP1LCH     EQU $080        ; Copper 1 list pointer high word
COP1LCL     EQU $082        ; Copper 1 list pointer low word
COPJMP1     EQU $088        ; Strobe: restart Copper 1 (any write)
DIWSTRT     EQU $08E        ; Display window start
DIWSTOP     EQU $090        ; Display window stop
DDFSTRT     EQU $092        ; Bitplane DMA start
DDFSTOP     EQU $094        ; Bitplane DMA stop
DMACON      EQU $096        ; DMA control (write)
INTENA      EQU $09A        ; Interrupt enable (write)
INTREQ      EQU $09C        ; Interrupt request (write)
BPLCON0     EQU $100        ; Bitplane control 0
BPLCON1     EQU $102        ; Bitplane control 1
BPLCON2     EQU $104        ; Bitplane control 2
BPL1MOD     EQU $108        ; Bitplane odd modulo
BPL2MOD     EQU $10A        ; Bitplane even modulo
COLOR00     EQU $180        ; Color register 0 (background)

; ── DMA Control Bits (DMACON / DMACONR) ─────────────────────────────────────
DMAF_SETCLR EQU $8000       ; Bit 15: 1=set named bits, 0=clear named bits
DMAF_MASTER EQU $0200       ; Bit  9: Master DMA enable (required for any DMA)
DMAF_BPLEN  EQU $0100       ; Bit  8: Bitplane DMA enable
DMAF_COPEN  EQU $0080       ; Bit  7: Copper DMA enable
DMAF_BLTEN  EQU $0040       ; Bit  6: Blitter DMA enable
DMAF_SPREN  EQU $0020       ; Bit  5: Sprite DMA enable
DMAF_DSKEN  EQU $0010       ; Bit  4: Disk DMA enable

; ── Interrupt Control Bits (INTENA / INTREQ) ────────────────────────────────
INTF_SETCLR EQU $8000       ; Bit 15: 1=set named bits, 0=clear named bits
INTF_INTEN  EQU $4000       ; Bit 14: Master interrupt enable
INTF_EXTER  EQU $2000       ; Bit 13: External interrupt (Level 6)
INTF_DSKSYN EQU $1000       ; Bit 12: Disk sync
INTF_RBF    EQU $0800       ; Bit 11: Serial receive buffer full
INTF_AUD3   EQU $0400       ; Bit 10: Audio channel 3
INTF_AUD2   EQU $0200       ; Bit  9: Audio channel 2
INTF_AUD1   EQU $0100       ; Bit  8: Audio channel 1
INTF_AUD0   EQU $0080       ; Bit  7: Audio channel 0
INTF_BLIT   EQU $0040       ; Bit  6: Blitter finished
INTF_VERTB  EQU $0020       ; Bit  5: VBlank (Level 3 autovector)
INTF_COPER  EQU $0010       ; Bit  4: Copper
INTF_PORTS  EQU $0008       ; Bit  3: CIA-A (keyboard / mouse / joystick)
INTF_SOFT   EQU $0004       ; Bit  2: Software interrupt
INTF_DSKBLK EQU $0002       ; Bit  1: Disk block complete
INTF_TBE    EQU $0001       ; Bit  0: Serial transmit buffer empty

; ── Exec Library Vector Offsets (from ExecBase in a6) ───────────────────────
_LVOForbid  EQU -132        ; Forbid() — prevent task switches
_LVOPermit  EQU -138        ; Permit() — allow task switches again

; ── System Constants ─────────────────────────────────────────────────────────
CUSTOM      EQU $DFF000     ; Custom chip registers base address
ABSEXECBASE EQU 4           ; Location of ExecBase pointer (always $4)
VEC_LEVEL3  EQU $6C         ; 68000 Level-3 autovector address
                            ; (VBlank on Amiga, fires 50x/sec PAL)


; ============================================================================
;  CODE SECTION
; ============================================================================

        SECTION startup_code,CODE

; ── Entry Point ──────────────────────────────────────────────────────────────
; AmigaOS executes this as a CLI program entry point.
; On entry: a0 = command line, d0 = command line length, stack is valid.

        XDEF    start
start:
        move.l  a5,-(sp)                ; preserve a5 (callee-save)
        move.l  sp,_saved_sp            ; remember stack for clean exit

        lea     CUSTOM,a5               ; a5 = $DFF000 — held for entire run
        move.l  ABSEXECBASE.w,a6        ; a6 = ExecBase

        ; Stop AmigaOS scheduler so it cannot preempt us
        jsr     _LVOForbid(a6)

; ── Snapshot Hardware State ───────────────────────────────────────────────────
        ; Read current interrupt and DMA masks so we can restore them exactly.
        move.w  INTENAR(a5),_saved_intena
        move.w  DMACONR(a5),_saved_dmacon
        move.l  VEC_LEVEL3.w,_saved_lev3vec

; ── Disable All Interrupts and DMA ──────────────────────────────────────────
        ; Bit 15 = 0 → CLEAR mode: every named bit is turned OFF.
        ; Writing $7FFF clears bits 14-0 (all functional bits).
        move.w  #$7FFF,INTENA(a5)       ; disable all interrupt sources

        ; Acknowledge any interrupt that may already be pending.
        ; Written twice because the chip bus needs an extra cycle to settle.
        move.w  #$7FFF,INTREQ(a5)
        move.w  #$7FFF,INTREQ(a5)

        move.w  #$7FFF,DMACON(a5)       ; stop all DMA activity

; ── Install VBlank Interrupt Handler ─────────────────────────────────────────
        ; On the Amiga the 68000 exception vector table lives in Chip RAM
        ; at addresses $000000–$0003FF. VEC_LEVEL3 = $6C is the Level-3
        ; autovector, triggered by Agnus at the start of every VBlank.
        ; We write our handler address directly — no Exec API needed.
        move.l  #_lev3_handler,VEC_LEVEL3.w

        ; Start the frame counter from zero
        clr.l   _frame_count

; ── Enable Required DMA ──────────────────────────────────────────────────────
        ; Bit 15 = 1 (SETCLR) → SET the named bits.
        ; MASTER must be set or NO DMA channel works at all.
        ; We enable: Master, Copper, Bitplanes, Blitter.
        ; Sprites are OFF by default — graphics.s enables them if needed.
        move.w  #(DMAF_SETCLR|DMAF_MASTER|DMAF_COPEN|DMAF_BPLEN|DMAF_BLTEN),DMACON(a5)

; ── Enable VBlank Interrupt ───────────────────────────────────────────────────
        ; Master enable + VBlank source bit.
        move.w  #(INTF_SETCLR|INTF_INTEN|INTF_VERTB),INTENA(a5)

; ── Run The Generated Program ────────────────────────────────────────────────
        ; codegen.js emits _main_program with the translated Blitz2D code.
        ; When it executes an End / falls off the end, we come back here.
        bsr     _main_program

; ── Restore AmigaOS ──────────────────────────────────────────────────────────
_exit:
        XDEF    _exit

        ; Disable our hardware before restoring Exec's vectors
        move.w  #$7FFF,INTENA(a5)
        move.w  #$7FFF,INTREQ(a5)
        move.w  #$7FFF,INTREQ(a5)
        move.w  #$7FFF,DMACON(a5)

        ; Restore the Level-3 vector so AmigaOS resumes its own VBlank handling
        move.l  _saved_lev3vec,VEC_LEVEL3.w

        ; Re-enable the interrupt sources that were active on entry.
        ; OR in the SETCLR bit so the mask becomes a SET operation.
        move.w  _saved_intena,d0
        or.w    #INTF_SETCLR,d0
        move.w  d0,INTENA(a5)

        ; Re-enable the DMA channels that were active on entry.
        move.w  _saved_dmacon,d0
        or.w    #DMAF_SETCLR,d0
        move.w  d0,DMACON(a5)

        ; Return the CPU to the AmigaOS scheduler
        move.l  ABSEXECBASE.w,a6
        jsr     _LVOPermit(a6)

        ; Unwind stack and return to AmigaOS CLI
        move.l  _saved_sp,sp
        move.l  (sp)+,a5
        moveq   #0,d0                   ; return code 0 = OK
        rts


; ============================================================================
;  LEVEL-3 VBLANK INTERRUPT HANDLER
; ============================================================================
;
; The Agnus chip fires the Level-3 interrupt at the top of each VBlank.
; On PAL machines this is exactly 50 times per second.
;
; Rules for interrupt handlers:
;   - MUST save and restore every register it touches
;   - MUST acknowledge the interrupt source before returning
;   - MUST end with RTE (not RTS — it's an exception return)
;   - Must NOT call WaitVBL (causes a deadlock)

_lev3_handler:
        movem.l d0-d7/a0-a5,-(sp)      ; save all scratch registers
        lea     CUSTOM,a5               ; establish custom base

        ; Acknowledge the VBlank interrupt.
        ; Writing a 1 to an INTREQ bit clears (acknowledges) it.
        ; On some chipset revisions a second write is needed.
        move.w  #INTF_VERTB,INTREQ(a5)
        move.w  #INTF_VERTB,INTREQ(a5)

        ; Advance the frame counter — WaitVBL polls this
        addq.l  #1,_frame_count

        ; Call the optional user VBlank hook if one is registered
        move.l  _vblank_hook,d0
        beq.s   .skip_hook
        move.l  d0,a0
        jsr     (a0)
.skip_hook:
        movem.l (sp)+,d0-d7/a0-a5      ; restore all registers
        rte                             ; return from exception


; ============================================================================
;  UTILITY SUBROUTINES
; ============================================================================

; ── _WaitVBL ─────────────────────────────────────────────────────────────────
; Block until the next VBlank fires. Typically called at the end of each
; game loop iteration to synchronise to the 50Hz display rate.
;
; Generated Blitz2D "WaitVbl" maps directly to this.
;
; Usage:    bsr  _WaitVBL
; Trashes:  d0

        XDEF    _WaitVBL
_WaitVBL:
        move.l  _frame_count,d0         ; capture current frame number
.poll:  cmp.l   _frame_count,d0        ; has VBlank fired yet?
        beq.s   .poll                   ; no — spin
        rts                             ; yes — return to caller


; ── _GetFrameCount ───────────────────────────────────────────────────────────
; Return the number of VBlanks since startup. Useful for time-based logic:
;   50 frames = 1 second  |  25 frames = 0.5 seconds
;
; Usage:    bsr  _GetFrameCount
; Returns:  d0.l = frame count

        XDEF    _GetFrameCount
_GetFrameCount:
        move.l  _frame_count,d0
        rts


; ── _SetVBlankHook ───────────────────────────────────────────────────────────
; Register a subroutine to be called from inside the VBlank handler.
; The hook is called 50 times per second, synchronised to the display.
; Pass a0 = 0 to remove a previously registered hook.
;
; The hook MUST:
;   - Preserve every register it uses
;   - Execute quickly (well under one frame = 20ms)
;   - NOT call WaitVBL or any blocking routine
;
; Usage:    lea  my_hook,a0
;           bsr  _SetVBlankHook

        XDEF    _SetVBlankHook
_SetVBlankHook:
        move.l  a0,_vblank_hook
        rts


; ============================================================================
;  BSS — Zero-filled uninitialised storage
; ============================================================================

        SECTION startup_bss,BSS

_saved_sp:      ds.l    1   ; stack pointer at program entry (for clean exit)
_saved_intena:  ds.w    1   ; INTENAR snapshot (restored on exit)
_saved_dmacon:  ds.w    1   ; DMACONR snapshot (restored on exit)
_saved_lev3vec: ds.l    1   ; original Level-3 exception vector
_frame_count:   ds.l    1   ; VBlank counter — incremented 50x/sec by handler
_vblank_hook:   ds.l    1   ; optional callback address (0 = none)
