// ============================================================================
// codegen.js — BASSM AST → m68k Assembly
// ============================================================================
//
// Converts the AST produced by the Parser into a complete vasm-compatible
// m68k assembly source file that targets bare-metal OCS/ECS Amiga (PAL).
//
// OUTPUT STRUCTURE
//   1.  Header comment
//   2.  Screen EQUs  (computed from the Graphics statement)
//   3.  Fragment INCLUDEs
//   4.  Chip-RAM BSS section  (_gfx_planes)
//   5.  Chip-RAM DATA section (_gfx_copper)
//   6.  User variable BSS section  (_var_*)  — one ds.l per integer variable
//   7.  _setup_graphics CODE
//   8.  _main_program CODE   (one instruction sequence per Blitz2D statement)
//
// EXPRESSION EVALUATION CONVENTION
//   • All expressions evaluate to a 32-bit signed integer in d0.
//   • Temporaries are pushed on the system stack; the stack is always clean
//     at the point of any subroutine call.
//   • Comparison operators produce Blitz2D boolean values: -1 (true) / 0 (false).
//   • Multiplication uses muls.w (16×16→32); operands must fit in 16 bits.
//   • Division uses divs.w (32÷16→16q); operands must fit accordingly.
// ============================================================================

// ── Helpers ──────────────────────────────────────────────────────────────────

const hex = (n, digits = 4) =>
    n.toString(16).toUpperCase().padStart(digits, '0');

const pad = (s, w) => s.padEnd(w, ' ');

const copMove = (reg, val, comment) =>
    `        dc.w    $${hex(reg)},$${hex(val)}${comment ? `             ; ${comment}` : ''}`;

// ── Bitplane pointer register pairs (OCS, 1-indexed) ─────────────────────────

const BPL_PTR_REGS = [
    [0x00E0, 0x00E2],
    [0x00E4, 0x00E6],
    [0x00E8, 0x00EA],
    [0x00EC, 0x00EE],
    [0x00F0, 0x00F2],
    [0x00F4, 0x00F6],
];

// ── CodeGen class ─────────────────────────────────────────────────────────────

export class CodeGen {

    /**
     * Generate a complete m68k assembly source from a BASSM AST.
     *
     * @param {object[]} ast  Statement nodes from Parser.parse()
     * @returns {string}      Assembly source text
     */
    generate(ast) {
        // Reset per-compilation state
        this._labelCount  = 0;
        this._arrays      = new Map();  // name → size Expr (populated by _collectVars)
        this._usesRaster  = false;      // true if any CopperColor command present

        // ── Locate and validate the Graphics statement ────────────────────────
        const gfxStmt = ast.find(s => s && s.type === 'command' && s.name === 'graphics');
        if (!gfxStmt) {
            throw new Error('Every BASSM program must begin with a Graphics statement.');
        }

        const W = this._intArg(gfxStmt, 0, 'Graphics width');
        const H = this._intArg(gfxStmt, 1, 'Graphics height');
        const D = this._intArg(gfxStmt, 2, 'Graphics depth');

        if (W !== 320) {
            throw new Error(`Graphics width ${W} not supported — only 320px lores OCS.`);
        }
        if (D < 1 || D > 6) {
            throw new Error(`Graphics depth ${D} out of range — must be 1–6 bitplanes.`);
        }

        // ── Display timing constants ──────────────────────────────────────────
        const colors  = 1 << D;
        const bplcon0 = (D << 12) | 0x0200;
        const hStart  = 0x81;
        const vStart  = 0x2C;
        const diwstrt = (vStart << 8) | hStart;
        const hStop   = (hStart + W) & 0xFF;
        const vStop   = (vStart + H) & 0xFF;
        const diwstop = (vStop  << 8) | hStop;
        const ddfstrt = 0x003C;
        const ddfstop = 0x00D4;

        // ── Collect scalar variable names and array declarations ─────────────
        const varNames = new Set();
        this._collectVars(ast, varNames);

        // ── Build output ──────────────────────────────────────────────────────
        const out = [];

        out.push('; ============================================================');
        out.push('; Generated by BASSM — do not edit');
        out.push(`; Screen: ${W}×${H}, ${D} bitplane${D > 1 ? 's' : ''}, ${colors} colours (PAL lores OCS)`);
        out.push('; ============================================================');
        out.push('');

        // EQUs
        out.push(`${pad('GFXWIDTH',12)} EQU ${W}`);
        out.push(`${pad('GFXHEIGHT',12)} EQU ${H}`);
        out.push(`${pad('GFXDEPTH',12)} EQU ${D}`);
        out.push(`${pad('GFXBPR',12)} EQU (GFXWIDTH/8)`);
        out.push(`${pad('GFXPSIZE',12)} EQU (GFXBPR*GFXHEIGHT)`);
        out.push(`${pad('GFXCOLORS',12)} EQU (1<<GFXDEPTH)`);
        out.push(`${pad('GFXBPLCON0',12)} EQU $${hex(bplcon0)}`);
        out.push(`${pad('GFXDIWSTRT',12)} EQU $${hex(diwstrt)}`);
        out.push(`${pad('GFXDIWSTOP',12)} EQU $${hex(diwstop)}`);
        out.push(`${pad('GFXDDFSTRT',12)} EQU $${hex(ddfstrt)}`);
        out.push(`${pad('GFXDDFSTOP',12)} EQU $${hex(ddfstop)}`);
        if (this._usesRaster) {
            const maxLines = Math.min(H, 256 - vStart);
            out.push(`${pad('GFXRASTER',12)} EQU ${maxLines}`);
        }
        out.push('');

        // Fragment INCLUDEs
        out.push('        INCLUDE "startup.s"');
        out.push('        INCLUDE "offload.s"');
        out.push('        INCLUDE "graphics.s"');
        out.push('        INCLUDE "cls.s"');
        out.push('        INCLUDE "clscolor.s"');
        out.push('        INCLUDE "color.s"');
        out.push('        INCLUDE "palette.s"');
        out.push('        INCLUDE "text.s"');
        out.push('        INCLUDE "plot.s"');
        out.push('        INCLUDE "line.s"');
        out.push('        INCLUDE "rect.s"');
        out.push('        INCLUDE "box.s"');
        out.push('        INCLUDE "waitkey.s"');
        out.push('        INCLUDE "flip.s"');
        if (this._usesRaster) {
            out.push('        INCLUDE "copper_raster.s"');
        }
        out.push('');
        out.push('        even');
        out.push('');

        // _setup_graphics subroutine
        out.push('        SECTION gfx_init,CODE');
        out.push('');
        out.push('_setup_graphics:');
        out.push('        lea     _gfx_cop_a_bpl_table,a0');
        out.push('        lea     _gfx_planes,a1');
        out.push('        moveq   #GFXDEPTH,d0');
        out.push('        move.l  #GFXPSIZE,d1');
        out.push('        jsr     _PatchBitplanePtrs');
        out.push('        lea     _gfx_cop_b_bpl_table,a0');
        out.push('        lea     _gfx_planes_b,a1');
        out.push('        moveq   #GFXDEPTH,d0');
        out.push('        move.l  #GFXPSIZE,d1');
        out.push('        jsr     _PatchBitplanePtrs');
        out.push('        lea     _gfx_copper_a,a0');
        out.push('        jsr     _InstallCopper');
        out.push('        jsr     _InitPalette');
        out.push('        lea     _gfx_planes_b,a0');
        out.push('        move.l  a0,_back_planes_ptr');
        out.push('        clr.b   _front_is_a');
        out.push('        rts');
        out.push('');

        // _main_program
        out.push('');
        out.push('        XDEF    _main_program');
        out.push('_main_program:');

        for (const stmt of ast) {
            if (!stmt) continue;
            out.push(...this._genStatement(stmt));
        }
        out.push('        rts');
        out.push('');

        // ── DATA & BSS SECTIONS (Must come after CODE for WinUAE compatibility) ──

        // User variable BSS — one longword per scalar integer variable
        if (varNames.size > 0 || this._arrays.size > 0) {
            out.push('        SECTION user_vars,BSS');
            for (const name of varNames) {
                out.push(`_var_${name}:    ds.l    1`);
            }
            // Arrays: Dim arr(n) → n+1 longwords (indices 0..n, Blitz2D-compatible)
            for (const [name, sizeExpr] of this._arrays) {
                if (sizeExpr.type !== 'int') {
                    throw new Error(`Dim ${name}: array size must be an integer literal`);
                }
                out.push(`_arr_${name}:    ds.l    ${sizeExpr.value + 1}`);
            }
            out.push('');
        }

        // Chip-RAM BSS — two bitplane buffers (A = front, B = back initially)
        out.push('        SECTION gfx_planes,BSS_C');
        out.push('_gfx_planes:    ds.b  GFXPSIZE*GFXDEPTH');
        out.push('_gfx_planes_b:  ds.b  GFXPSIZE*GFXDEPTH');
        out.push('');

        // Helper: emit display-setup copper moves (shared header for both lists)
        const emitCopHeader = () => {
            out.push(copMove(0x008E, diwstrt, 'DIWSTRT'));
            out.push(copMove(0x0090, diwstop, 'DIWSTOP'));
            out.push(copMove(0x0092, ddfstrt, 'DDFSTRT'));
            out.push(copMove(0x0094, ddfstop, 'DDFSTOP'));
            out.push(copMove(0x0100, bplcon0, 'BPLCON0'));
            out.push(copMove(0x0102, 0x0000,  'BPLCON1'));
            out.push(copMove(0x0104, 0x0000,  'BPLCON2'));
            out.push(copMove(0x0108, 0x0000,  'BPL1MOD'));
            out.push(copMove(0x010A, 0x0000,  'BPL2MOD'));
        };

        // Chip-RAM DATA — copper list A (bitplane pointers → buffer A)
        out.push('        SECTION gfx_copper,DATA_C');
        out.push('_gfx_copper_a:');
        emitCopHeader();
        out.push('_gfx_cop_a_bpl_table:');
        for (let i = 0; i < D; i++) {
            const [pth, ptl] = BPL_PTR_REGS[i];
            out.push(copMove(pth, 0, `BPL${i+1}PTH`));
            out.push(copMove(ptl, 0, `BPL${i+1}PTL`));
        }
        if (this._usesRaster) {
            const maxLines = Math.min(H, 256 - vStart);
            out.push('        XDEF    _gfx_raster_a');
            out.push('_gfx_raster_a:');
            for (let y = 0; y < maxLines; y++) {
                const vpos = vStart + y;
                out.push(`        dc.w    $${hex((vpos << 8) | 0x01)},$FF00`);
                out.push(`        dc.w    $0180,$0000`);
            }
        }
        out.push('        dc.w    $FFFF,$FFFE             ; END of copper list A');
        out.push('');

        // Chip-RAM DATA — copper list B (bitplane pointers → buffer B)
        out.push('_gfx_copper_b:');
        emitCopHeader();
        out.push('_gfx_cop_b_bpl_table:');
        for (let i = 0; i < D; i++) {
            const [pth, ptl] = BPL_PTR_REGS[i];
            out.push(copMove(pth, 0, `BPL${i+1}PTH`));
            out.push(copMove(ptl, 0, `BPL${i+1}PTL`));
        }
        if (this._usesRaster) {
            const maxLines = Math.min(H, 256 - vStart);
            out.push('        XDEF    _gfx_raster_b');
            out.push('_gfx_raster_b:');
            for (let y = 0; y < maxLines; y++) {
                const vpos = vStart + y;
                out.push(`        dc.w    $${hex((vpos << 8) | 0x01)},$FF00`);
                out.push(`        dc.w    $0180,$0000`);
            }
        }
        out.push('        dc.w    $FFFF,$FFFE             ; END of copper list B');
        out.push('');

        return out.join('\n');
    }

    // ── Variable collection (pre-pass) ────────────────────────────────────────
    //
    // Walks the AST and collects all variable names so we can emit BSS
    // declarations before _main_program.

    _collectVars(ast, varSet) {
        for (const stmt of ast) {
            if (!stmt) continue;
            if (stmt.type === 'assign') {
                varSet.add(stmt.target);
                this._collectVarsInExpr(stmt.expr, varSet);
            } else if (stmt.type === 'dim') {
                this._arrays.set(stmt.name, stmt.size);
            } else if (stmt.type === 'array_assign') {
                this._collectVarsInExpr(stmt.index, varSet);
                this._collectVarsInExpr(stmt.expr,  varSet);
            } else if (stmt.type === 'command') {
                if (stmt.name === 'coppercolor') this._usesRaster = true;
                for (const arg of stmt.args) {
                    this._collectVarsInExpr(arg, varSet);
                }
            } else if (stmt.type === 'if') {
                this._collectVarsInExpr(stmt.cond, varSet);
                this._collectVars(stmt.then, varSet);
                for (const ei of stmt.elseIfs) {
                    this._collectVarsInExpr(ei.cond, varSet);
                    this._collectVars(ei.body, varSet);
                }
                this._collectVars(stmt.else, varSet);
            } else if (stmt.type === 'while') {
                this._collectVarsInExpr(stmt.cond, varSet);
                this._collectVars(stmt.body, varSet);
            } else if (stmt.type === 'for') {
                varSet.add(stmt.var);
                this._collectVarsInExpr(stmt.from, varSet);
                this._collectVarsInExpr(stmt.to,   varSet);
                if (stmt.step) this._collectVarsInExpr(stmt.step, varSet);
                this._collectVars(stmt.body, varSet);
            } else if (stmt.type === 'select') {
                this._collectVarsInExpr(stmt.expr, varSet);
                for (const c of stmt.cases) {
                    for (const v of c.values) this._collectVarsInExpr(v, varSet);
                    this._collectVars(c.body, varSet);
                }
                this._collectVars(stmt.default, varSet);
            }
        }
    }

    _collectVarsInExpr(expr, varSet) {
        if (!expr) return;
        switch (expr.type) {
            case 'ident':
                varSet.add(expr.name);
                break;
            case 'array_read':
                // array name is NOT a scalar — only collect vars used in the index
                this._collectVarsInExpr(expr.index, varSet);
                break;
            case 'binop':
                this._collectVarsInExpr(expr.left,    varSet);
                this._collectVarsInExpr(expr.right,   varSet);
                break;
            case 'unary':
                this._collectVarsInExpr(expr.operand, varSet);
                break;
        }
    }

    // ── Per-statement code generation ─────────────────────────────────────────

    _genStatement(stmt) {
        const lines = [];

        // ── Variable assignment: target = expr ───────────────────────────────
        if (stmt.type === 'assign') {
            this._genExpr(stmt.expr, lines);
            lines.push(`        move.l  d0,_var_${stmt.target}`);
            return lines;
        }

        // ── Dim — declaration only, no code emitted ───────────────────────────
        if (stmt.type === 'dim') {
            return lines;
        }

        // ── Array assignment: arr(index) = expr ──────────────────────────────
        // Evaluate expr → push; evaluate index → d0; compute address; store.
        if (stmt.type === 'array_assign') {
            this._genExpr(stmt.expr, lines);
            lines.push(`        move.l  d0,-(sp)`);
            this._genExpr(stmt.index, lines);
            lines.push(`        asl.l   #2,d0`);
            lines.push(`        lea     _arr_${stmt.name},a0`);
            lines.push(`        add.l   d0,a0`);
            lines.push(`        move.l  (sp)+,(a0)`);
            return lines;
        }

        // ── If / ElseIf / Else / EndIf ────────────────────────────────────────
        if (stmt.type === 'if') {
            this._genIf(stmt, lines);
            return lines;
        }

        // ── While / Wend ──────────────────────────────────────────────────────
        if (stmt.type === 'while') {
            this._genWhile(stmt, lines);
            return lines;
        }

        // ── For / To / Step / Next ────────────────────────────────────────────
        if (stmt.type === 'for') {
            this._genFor(stmt, lines);
            return lines;
        }

        // ── Select / Case / Default / EndSelect ───────────────────────────────
        if (stmt.type === 'select') {
            this._genSelect(stmt, lines);
            return lines;
        }

        if (stmt.type !== 'command') return lines;

        const name = stmt.name;

        switch (name) {

            case 'graphics':
                lines.push('        jsr     _setup_graphics');
                break;

            case 'cls':
                lines.push('        jsr     _Cls');
                break;

            case 'clscolor': {
                this._genExprArg(stmt, 0, 'ClsColor', lines);
                lines.push('        jsr     _ClsColor');
                break;
            }

            case 'color': {
                this._genExprArg(stmt, 0, 'Color', lines);
                lines.push('        move.w  d0,_draw_color');
                break;
            }

            case 'palettecolor': {
                // If all 4 args are compile-time literals, build the OCS word in the
                // assembler and call the lighter _SetPaletteColor directly (no subroutine
                // overhead for r/g/b assembly).
                // If any arg is a runtime expression, push b/g/r, evaluate n, pop into
                // d1-d3, then call _SetPaletteColorRGB which builds the OCS word at runtime.
                if (stmt.args.every(a => a.type === 'int')) {
                    const n   = stmt.args[0].value;
                    const r   = stmt.args[1].value & 0xF;
                    const g   = stmt.args[2].value & 0xF;
                    const b   = stmt.args[3].value & 0xF;
                    const rgb = (r << 8) | (g << 4) | b;
                    lines.push(`        moveq   #${n},d0`);
                    lines.push(`        move.w  #$${hex(rgb)},d1`);
                    lines.push('        jsr     _SetPaletteColor');
                } else {
                    // Evaluate b, g, r and push; evaluate n last (d0=n after push/pop).
                    // movem.l (sp)+,d1-d3 pops in register order: d1=r, d2=g, d3=b.
                    this._genExprArg(stmt, 3, 'PaletteColor b', lines);
                    lines.push('        move.l  d0,-(sp)');
                    this._genExprArg(stmt, 2, 'PaletteColor g', lines);
                    lines.push('        move.l  d0,-(sp)');
                    this._genExprArg(stmt, 1, 'PaletteColor r', lines);
                    lines.push('        move.l  d0,-(sp)');
                    this._genExprArg(stmt, 0, 'PaletteColor n', lines);  // d0 = n
                    lines.push('        movem.l (sp)+,d1-d3');            // d1=r, d2=g, d3=b
                    lines.push('        jsr     _SetPaletteColorRGB');
                }
                break;
            }

            case 'end':
                lines.push('        rts');
                break;

            case 'delay': {
                // Delay n — wait n VBlanks.  n may be any integer expression.
                const loopLbl = this._nextLabel();
                const skipLbl = this._nextLabel();
                this._genExprArg(stmt, 0, 'Delay frames', lines);
                // Guard: skip loop if n <= 0
                lines.push(`        tst.l   d0`);
                lines.push(`        ble.s   ${skipLbl}`);
                lines.push(`        subq.l  #1,d0`);
                lines.push(`        move.l  d0,d7`);
                lines.push(`${loopLbl}:`);
                lines.push(`        jsr     _WaitVBL`);
                lines.push(`        dbra    d7,${loopLbl}`);
                lines.push(`${skipLbl}:`);
                break;
            }

            case 'waitvbl':
                lines.push('        jsr     _WaitVBL');
                break;

            case 'waitkey':
                lines.push('        jsr     _WaitKey');
                break;

            case 'screenflip':
                lines.push('        jsr     _ScreenFlip');
                break;

            case 'coppercolor': {
                // CopperColor y,r,g,b — patch COLOR00 MOVE entry at scanline y
                // in the back copper list (visible after next ScreenFlip).
                // Compile-time path: all 4 args are integer literals.
                // Runtime path: any arg is a variable/expression.
                if (stmt.args.every(a => a.type === 'int')) {
                    const y   = stmt.args[0].value;
                    const r   = stmt.args[1].value & 0xF;
                    const g   = stmt.args[2].value & 0xF;
                    const b   = stmt.args[3].value & 0xF;
                    const rgb = (r << 8) | (g << 4) | b;
                    lines.push(`        moveq   #${y},d0`);
                    lines.push(`        move.w  #$${hex(rgb)},d1`);
                    lines.push('        jsr     _SetRasterColor');
                } else {
                    // Push b, g, r; eval y → d0; movem pops d1=r, d2=g, d3=b
                    this._genExprArg(stmt, 3, 'CopperColor b', lines);
                    lines.push('        move.l  d0,-(sp)');
                    this._genExprArg(stmt, 2, 'CopperColor g', lines);
                    lines.push('        move.l  d0,-(sp)');
                    this._genExprArg(stmt, 1, 'CopperColor r', lines);
                    lines.push('        move.l  d0,-(sp)');
                    this._genExprArg(stmt, 0, 'CopperColor y', lines);  // d0 = y
                    lines.push('        movem.l (sp)+,d1-d3');           // d1=r, d2=g, d3=b
                    lines.push('        jsr     _SetRasterColorRGB');
                }
                break;
            }

            case 'text': {
                const str     = this._strArg(stmt, 2, 'Text string');
                const strLbl  = this._nextLabel();
                const pastLbl = this._nextLabel();
                // _Text(a0=str, d0=x, d1=y)
                // Evaluate y first (save it), then x, then move y to d1
                this._genExprArg(stmt, 1, 'Text y', lines);
                lines.push(`        move.l  d0,-(sp)`);
                this._genExprArg(stmt, 0, 'Text x', lines);
                lines.push(`        move.l  (sp)+,d1`);
                lines.push(`        lea     ${strLbl},a0`);
                lines.push(`        jsr     _Text`);
                lines.push(`        bra.s   ${pastLbl}`);
                lines.push(`${strLbl}:`);
                lines.push(`        dc.b    "${this._escapeStr(str)}",0`);
                lines.push('        even');
                lines.push(`${pastLbl}:`);
                break;
            }

            case 'nprint': {
                const str     = this._strArg(stmt, 0, 'NPrint string');
                const strLbl  = this._nextLabel();
                const pastLbl = this._nextLabel();
                lines.push(`        lea     ${strLbl},a0`);
                lines.push('        jsr     _NPrint');
                lines.push(`        bra.s   ${pastLbl}`);
                lines.push(`${strLbl}:`);
                lines.push(`        dc.b    "${this._escapeStr(str)}",0`);
                lines.push('        even');
                lines.push(`${pastLbl}:`);
                break;
            }

            // ── Drawing commands ──────────────────────────────────────────────

            case 'plot': {
                // Plot x, y  →  _Plot(d0=x, d1=y)
                // Evaluate y first (push), then x → d0, pop y → d1
                this._genExprArg(stmt, 1, 'Plot y', lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExprArg(stmt, 0, 'Plot x', lines);
                lines.push('        move.l  (sp)+,d1');
                lines.push('        jsr     _Plot');
                break;
            }

            case 'line': {
                // Line x1,y1,x2,y2  →  _Line(d0=x1, d1=y1, d2=x2, d3=y2)
                // Push y2, x2, y1; then x1 → d0; pop y1→d1, x2→d2, y2→d3
                this._genExprArg(stmt, 3, 'Line y2', lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExprArg(stmt, 2, 'Line x2', lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExprArg(stmt, 1, 'Line y1', lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExprArg(stmt, 0, 'Line x1', lines);
                lines.push('        movem.l (sp)+,d1-d3');
                lines.push('        jsr     _Line');
                break;
            }

            case 'rect': {
                // Rect x,y,w,h  →  _Rect(d0=x, d1=y, d2=w, d3=h)
                // Push h, w, y; then x → d0; pop y→d1, w→d2, h→d3
                this._genExprArg(stmt, 3, 'Rect h', lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExprArg(stmt, 2, 'Rect w', lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExprArg(stmt, 1, 'Rect y', lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExprArg(stmt, 0, 'Rect x', lines);
                lines.push('        movem.l (sp)+,d1-d3');
                lines.push('        jsr     _Rect');
                break;
            }

            case 'box': {
                // Box x,y,w,h  →  _Box(d0=x, d1=y, d2=w, d3=h)
                // Push h, w, y; then x → d0; pop y→d1, w→d2, h→d3
                this._genExprArg(stmt, 3, 'Box h', lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExprArg(stmt, 2, 'Box w', lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExprArg(stmt, 1, 'Box y', lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExprArg(stmt, 0, 'Box x', lines);
                lines.push('        movem.l (sp)+,d1-d3');
                lines.push('        jsr     _Box');
                break;
            }

            default:
                lines.push(`; [codegen] Unhandled command: ${stmt.name} (line ${stmt.line})`);
                console.warn(`[CodeGen] No codegen for '${stmt.name}' on line ${stmt.line}`);
        }

        return lines;
    }

    // ── If statement code generation ──────────────────────────────────────────
    //
    // Evaluates cond into d0; tst.l; beq.w branches to else/endif.
    // Uses .w branches so bodies can be arbitrarily large.

    _genIf(stmt, lines) {
        const hasElseIf = stmt.elseIfs.length > 0;
        const hasElse   = stmt.else.length > 0;
        const endLbl    = this._nextLabel();

        if (hasElseIf || hasElse) {
            const firstAltLbl = this._nextLabel();
            // PERF-A: emit cmp+Bcc directly for comparison conditions
            this._genCondBranch(stmt.cond, firstAltLbl, lines);

            // Then body
            for (const s of stmt.then) lines.push(...this._genStatement(s));
            lines.push(`        bra.w   ${endLbl}`);
            lines.push(`${firstAltLbl}:`);

            // ElseIf chain — each produces its own branch-to-endif
            for (const ei of stmt.elseIfs) {
                const nextAltLbl = this._nextLabel();
                this._genCondBranch(ei.cond, nextAltLbl, lines);
                for (const s of ei.body) lines.push(...this._genStatement(s));
                lines.push(`        bra.w   ${endLbl}`);
                lines.push(`${nextAltLbl}:`);
            }

            // Else body (empty if none)
            for (const s of stmt.else) lines.push(...this._genStatement(s));
        } else {
            // Simple If without any alternate branch
            this._genCondBranch(stmt.cond, endLbl, lines);
            for (const s of stmt.then) lines.push(...this._genStatement(s));
        }

        lines.push(`${endLbl}:`);
    }

    // ── While statement code generation ───────────────────────────────────────
    //
    // While <cond> … Wend
    //   Condition is re-evaluated at the top of every iteration.

    _genWhile(stmt, lines) {
        const topLbl = this._nextLabel();

        // Constant-true condition (While 1, While -1, …): no test needed.
        // Emits just a top label + body + unconditional branch — saves 3 instructions
        // per iteration compared to the generic moveq/tst.l/beq.w sequence.
        if (stmt.cond.type === 'int' && stmt.cond.value !== 0) {
            lines.push(`${topLbl}:`);
            for (const s of stmt.body) lines.push(...this._genStatement(s));
            lines.push(`        bra.w   ${topLbl}`);
            return;
        }

        const endLbl = this._nextLabel();

        lines.push(`${topLbl}:`);
        // PERF-A: emit cmp+Bcc directly for comparison conditions
        this._genCondBranch(stmt.cond, endLbl, lines);

        for (const s of stmt.body) lines.push(...this._genStatement(s));

        lines.push(`        bra.w   ${topLbl}`);
        lines.push(`${endLbl}:`);
    }

    // ── For statement code generation ─────────────────────────────────────────
    //
    // For <var> = <from> To <to> [Step <step>] … Next [<var>]
    //
    // Literal step (known at compile time):
    //   Step >= 0 → bgt.w to exit; addq.l / add.l for increment.
    //   Step <  0 → blt.w to exit; subq.l / sub.l for decrement.
    //
    // Expression step (not a literal integer):
    //   Runtime sign check — re-evaluates step and limit each iteration.

    _genFor(stmt, lines) {
        const topLbl = this._nextLabel();
        const endLbl = this._nextLabel();

        // Determine step value at compile time (null = unknown / expression)
        const stepLit = stmt.step === null       ? 1
                      : stmt.step.type === 'int' ? stmt.step.value
                      :                            null;

        // Initialise loop variable
        this._genExpr(stmt.from, lines);
        lines.push(`        move.l  d0,_var_${stmt.var}`);

        lines.push(`${topLbl}:`);

        if (stepLit !== null) {
            // ── Literal step: direction known at compile time ─────────────────
            this._genExpr(stmt.to, lines);
            lines.push('        move.l  d0,-(sp)');
            lines.push(`        move.l  _var_${stmt.var},d0`);
            lines.push('        move.l  (sp)+,d1');        // d0=i, d1=limit
            lines.push('        cmp.l   d1,d0');            // i - limit
            lines.push(stepLit >= 0
                ? `        bgt.w   ${endLbl}`              // i > limit → exit
                : `        blt.w   ${endLbl}`);            // i < limit → exit

            for (const s of stmt.body) lines.push(...this._genStatement(s));

            // Step increment / decrement
            const av = Math.abs(stepLit);
            if (av >= 1 && av <= 8) {
                const op = stepLit > 0 ? 'addq.l' : 'subq.l';
                lines.push(`        ${op}  #${av},_var_${stmt.var}`);
            } else {
                lines.push(`        move.l  _var_${stmt.var},d0`);
                lines.push(`        add.l   #${stepLit},d0`);
                lines.push(`        move.l  d0,_var_${stmt.var}`);
            }

        } else {
            // ── Expression step: runtime sign check ───────────────────────────
            const negLbl  = this._nextLabel();
            const bodyLbl = this._nextLabel();

            // Check sign of step to pick branch direction
            this._genExpr(stmt.step, lines);
            lines.push('        tst.l   d0');
            lines.push(`        bmi.s   ${negLbl}`);       // step < 0?

            // step >= 0: exit if i > limit
            this._genExpr(stmt.to, lines);
            lines.push('        move.l  d0,-(sp)');
            lines.push(`        move.l  _var_${stmt.var},d0`);
            lines.push('        move.l  (sp)+,d1');
            lines.push('        cmp.l   d1,d0');
            lines.push(`        bgt.w   ${endLbl}`);
            lines.push(`        bra.s   ${bodyLbl}`);

            lines.push(`${negLbl}:`);
            // step < 0: exit if i < limit
            this._genExpr(stmt.to, lines);
            lines.push('        move.l  d0,-(sp)');
            lines.push(`        move.l  _var_${stmt.var},d0`);
            lines.push('        move.l  (sp)+,d1');
            lines.push('        cmp.l   d1,d0');
            lines.push(`        blt.w   ${endLbl}`);

            lines.push(`${bodyLbl}:`);
            for (const s of stmt.body) lines.push(...this._genStatement(s));

            // Step: i += step (re-evaluate)
            this._genExpr(stmt.step, lines);
            lines.push(`        add.l   _var_${stmt.var},d0`);
            lines.push(`        move.l  d0,_var_${stmt.var}`);
        }

        lines.push(`        bra.w   ${topLbl}`);
        lines.push(`${endLbl}:`);
    }

    // ── Select statement code generation ─────────────────────────────────────
    //
    // Select <expr>
    //   Case <val>[, <val>…]  — multiple values per Case share one jump target
    //   Default
    // EndSelect
    //
    // Pattern:
    //   Evaluate selector → push on stack.
    //   Comparison chain: for each Case value, peek selector, compare, beq.w.
    //   No match → bra.w to default or end.
    //   Case bodies follow, each ending with bra.w to end.
    //   Default body (if any).
    //   End label + addq.l #4,sp (pop selector).
    //
    // For literal integer Case values: optimised to move.l (sp),d0 / cmp.l #n,d0.
    // For expression values: general 4-instruction push/peek/pop/cmp sequence.

    _genSelect(stmt, lines) {
        const endLbl  = this._nextLabel();
        const defLbl  = stmt.default.length > 0 ? this._nextLabel() : endLbl;

        // Evaluate selector → push on stack
        this._genExpr(stmt.expr, lines);
        lines.push('        move.l  d0,-(sp)');

        // Assign one label per Case block
        const caseLabels = stmt.cases.map(() => this._nextLabel());

        // ── Comparison chain ──────────────────────────────────────────────────
        for (let i = 0; i < stmt.cases.length; i++) {
            const caseLbl = caseLabels[i];
            for (const val of stmt.cases[i].values) {
                if (val.type === 'int') {
                    // Optimised: peek selector, compare with immediate
                    lines.push('        move.l  (sp),d0');
                    lines.push(`        cmp.l   #${val.value},d0`);
                } else {
                    // General: eval value → push; peek selector; pop value → d1; cmp
                    this._genExpr(val, lines);              // value → d0
                    lines.push('        move.l  d0,-(sp)'); // push value
                    lines.push('        move.l  4(sp),d0'); // peek selector (below value)
                    lines.push('        move.l  (sp)+,d1'); // pop value → d1
                    lines.push('        cmp.l   d1,d0');    // selector - value
                }
                lines.push(`        beq.w   ${caseLbl}`);
            }
        }
        // No match → jump to default (or end if none)
        lines.push(`        bra.w   ${defLbl}`);

        // ── Case bodies ───────────────────────────────────────────────────────
        for (let i = 0; i < stmt.cases.length; i++) {
            lines.push(`${caseLabels[i]}:`);
            for (const s of stmt.cases[i].body) lines.push(...this._genStatement(s));
            lines.push(`        bra.w   ${endLbl}`);
        }

        // ── Default body ──────────────────────────────────────────────────────
        if (stmt.default.length > 0) {
            lines.push(`${defLbl}:`);
            for (const s of stmt.default) lines.push(...this._genStatement(s));
        }

        // ── Pop selector + end ────────────────────────────────────────────────
        lines.push(`${endLbl}:`);
        lines.push('        addq.l  #4,sp');
    }

    // ── Expression code generation ────────────────────────────────────────────
    //
    // Emits code that evaluates `expr` and leaves the result in d0.
    // Uses the system stack for sub-expression temporaries.

    _genExpr(expr, lines) {
        if (!expr) {
            lines.push('        moveq   #0,d0');
            return;
        }

        switch (expr.type) {

            case 'int':
                if (expr.value >= -128 && expr.value <= 127) {
                    lines.push(`        moveq   #${expr.value},d0`);
                } else {
                    lines.push(`        move.l  #${expr.value},d0`);
                }
                break;

            case 'ident':
                lines.push(`        move.l  _var_${expr.name},d0`);
                break;

            case 'array_read':
                // Evaluate index → d0; multiply by 4; offset from array base.
                this._genExpr(expr.index, lines);
                lines.push(`        asl.l   #2,d0`);
                lines.push(`        lea     _arr_${expr.name},a0`);
                lines.push(`        add.l   d0,a0`);
                lines.push(`        move.l  (a0),d0`);
                break;

            case 'unary':
                if (expr.op === '-') {
                    this._genExpr(expr.operand, lines);
                    lines.push('        neg.l   d0');
                }
                break;

            case 'binop':
                this._genBinop(expr, lines);
                break;

            case 'float':
                throw new Error(`Float expressions are not yet supported (line ${expr.line ?? '?'})`);

            case 'string':
                throw new Error(`String expressions cannot be used as integer values`);

            default:
                lines.push('        moveq   #0,d0');
                console.warn(`[CodeGen] Unknown expression type: ${expr.type}`);
        }
    }

    // ── PERF-B helpers ────────────────────────────────────────────────────────

    /** True when expr is a compile-time constant or a single variable reference.
     *  These can be used directly as m68k immediate/memory operands — no push/pop needed. */
    _isSimpleExpr(expr) {
        return expr.type === 'int' || expr.type === 'ident';
    }

    /** Return the m68k source operand string for a simple expression. */
    _simpleOperand(expr) {
        if (expr.type === 'int')   return `#${expr.value}`;
        if (expr.type === 'ident') return `_var_${expr.name}`;
        throw new Error('[CodeGen] _simpleOperand called on non-simple expr');
    }

    // ── PERF-A: direct conditional branch ────────────────────────────────────
    //
    // When the condition is a direct comparison (binop = <> < > <= >=) this
    // emits a CMP + Bcc pair instead of the Scc + ext.w + ext.l + tst.l + beq.w
    // sequence, saving 4 instructions per conditional every iteration.
    //
    // falseLbl: label to branch to when the condition is FALSE (i.e. the
    //           inverse branch: if `a < b` → jump when a >= b → bge).
    //
    // Only call this for conditions inside If/While, NOT when a comparison
    // result is used as a value (e.g. `x = a < b`).

    _genCondBranch(expr, falseLbl, lines) {
        // Map each operator to the Bcc that branches on the OPPOSITE condition.
        const bccFalseMap = {
            '=':  'bne', '<>': 'beq',
            '<':  'bge', '>':  'ble',
            '<=': 'bgt', '>=': 'blt',
        };

        if (expr.type === 'binop' && bccFalseMap[expr.op]) {
            if (this._isSimpleExpr(expr.right)) {
                // PERF-A + PERF-B: load left → d0, cmp immediate/memory, branch
                this._genExpr(expr.left, lines);
                lines.push(`        cmp.l   ${this._simpleOperand(expr.right)},d0`);
            } else {
                // PERF-A only: generic eval — push right, load left, pop d1, cmp
                this._genExpr(expr.right, lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExpr(expr.left, lines);
                lines.push('        move.l  (sp)+,d1');
                lines.push('        cmp.l   d1,d0');
            }
            lines.push(`        ${bccFalseMap[expr.op]}.w   ${falseLbl}`);
            return;
        }

        // Fallback: evaluate expression as boolean value, test, branch
        this._genExpr(expr, lines);
        lines.push('        tst.l   d0');
        lines.push(`        beq.w   ${falseLbl}`);
    }

    _genBinop(expr, lines) {
        const op = expr.op;

        // ── Arithmetic: + - ───────────────────────────────────────────────────
        // PERF-B: if right is a literal or single ident, skip push/pop entirely.
        if (op === '+' || op === '-') {
            if (this._isSimpleExpr(expr.right)) {
                this._genExpr(expr.left, lines);
                const v = expr.right;
                if (v.type === 'int' && v.value >= 1 && v.value <= 8) {
                    // addq/subq: 1-word instruction for 1..8
                    lines.push(`        ${op === '+' ? 'addq' : 'subq'}.l  #${v.value},d0`);
                } else {
                    lines.push(`        ${op === '+' ? 'add' : 'sub'}.l   ${this._simpleOperand(v)},d0`);
                }
            } else {
                this._genExpr(expr.right, lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExpr(expr.left, lines);
                lines.push('        move.l  (sp)+,d1');
                lines.push(`        ${op === '+' ? 'add' : 'sub'}.l   d1,d0`);
            }
            return;
        }

        // ── Arithmetic: * / ───────────────────────────────────────────────────
        // muls.w / divs.w require a register source — keep generic push/pop path.
        if (op === '*' || op === '/') {
            this._genExpr(expr.right, lines);
            lines.push('        move.l  d0,-(sp)');
            this._genExpr(expr.left, lines);
            lines.push('        move.l  (sp)+,d1');   // d0=left, d1=right
            if (op === '*') {
                // muls.w: d0.w × d1.w → d0.l (signed, 16×16→32)
                lines.push('        muls.w  d1,d0');
            } else {
                // divs.w: d0.l ÷ d1.w → d0.w quotient; ext.l to 32 bits
                lines.push('        divs.w  d1,d0');
                lines.push('        ext.l   d0');
            }
            return;
        }

        // ── Comparison: = <> < > <= >= ────────────────────────────────────────
        // Produces Blitz2D boolean: -1 (true) or 0 (false).
        // PERF-B: skip push/pop when right is a literal or single ident.
        const sccMap = {
            '=':  'seq',
            '<>': 'sne',
            '<':  'slt',
            '>':  'sgt',
            '<=': 'sle',
            '>=': 'sge',
        };
        if (sccMap[op]) {
            if (this._isSimpleExpr(expr.right)) {
                this._genExpr(expr.left, lines);
                lines.push(`        cmp.l   ${this._simpleOperand(expr.right)},d0`);
            } else {
                this._genExpr(expr.right, lines);
                lines.push('        move.l  d0,-(sp)');
                this._genExpr(expr.left, lines);
                lines.push('        move.l  (sp)+,d1');   // d0=left, d1=right
                lines.push('        cmp.l   d1,d0');       // flags: d0 - d1 (left - right)
            }
            lines.push(`        ${sccMap[op]}     d0`); // d0.b = $FF (true) or $00 (false)
            lines.push('        ext.w   d0');           // sign-extend to word
            lines.push('        ext.l   d0');           // sign-extend to long (-1 or 0)
            return;
        }

        lines.push('        moveq   #0,d0');
        console.warn(`[CodeGen] Unknown binary operator: '${op}'`);
    }

    // ── Argument helpers ──────────────────────────────────────────────────────

    /** Evaluate stmt.args[idx] into d0 via _genExpr. */
    _genExprArg(stmt, idx, label, lines) {
        const arg = stmt.args[idx];
        if (!arg) throw new Error(`${label}: missing argument at position ${idx} on line ${stmt.line}`);
        this._genExpr(arg, lines);
    }

    /** Extract a compile-time integer literal (for Graphics and similar). */
    _intArg(stmt, idx, label) {
        const arg = stmt.args[idx];
        if (!arg || arg.type !== 'int') {
            throw new Error(
                `${label}: expected integer literal at position ${idx} on line ${stmt.line}`
            );
        }
        return arg.value;
    }

    /** Extract a compile-time string literal. */
    _strArg(stmt, idx, label) {
        const arg = stmt.args[idx];
        if (!arg || arg.type !== 'string') {
            throw new Error(
                `${label}: expected string literal at position ${idx} on line ${stmt.line}`
            );
        }
        return arg.value;
    }

    /** Escape double-quotes and backslashes inside a dc.b string literal. */
    _escapeStr(s) {
        return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    }

    /** Return a globally unique local label string. */
    _nextLabel() {
        return `.L${this._labelCount++}`;
    }
}
