// ============================================================================
// codegen.js — BASSM AST → m68k Assembly
// ============================================================================
//
// Converts the AST produced by the Parser into a complete vasm-compatible
// m68k assembly source file that targets bare-metal OCS/ECS Amiga (PAL).
//
// OUTPUT STRUCTURE
//   1.  Header comment
//   2.  Screen EQUs  (computed from the Graphics statement)
//   3.  Fragment INCLUDEs  (startup, offload, graphics, cls, …)
//       NOTE: INCLUDEs use bare filenames — the vasm -I flag must point to
//       the fragments directory at assembly time.
//   4.  Chip-RAM BSS section  (_gfx_planes)
//   5.  Chip-RAM DATA section (_gfx_copper)
//   6.  _setup_graphics CODE  (patches copper + installs copper)
//   7.  _main_program CODE    (one instruction per Blitz2D statement)
//
// CONSTRAINTS (current)
//   • Width must be 320 pixels (lores OCS).  DDFSTRT/DDFSTOP are fixed.
//   • Depth 1–6 bitplanes.
//   • The Graphics statement must appear before any graphical commands.
// ============================================================================

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Zero-padded uppercase hex string, default 4 digits */
const hex = (n, digits = 4) =>
    n.toString(16).toUpperCase().padStart(digits, '0');

/** Pad a string on the right to a given width */
const pad = (s, w) => s.padEnd(w, ' ');

/** Emit a copper MOVE instruction: register-offset word + value word */
const copMove = (reg, val, comment) =>
    `        dc.w    $${hex(reg)},$${hex(val)}${comment ? `             ; ${comment}` : ''}`;

// ── Bitplane pointer register pairs (OCS, 1-indexed) ─────────────────────────

const BPL_PTR_REGS = [
    [0x00E0, 0x00E2],   // BPL1PTH / BPL1PTL
    [0x00E4, 0x00E6],   // BPL2PTH / BPL2PTL
    [0x00E8, 0x00EA],   // BPL3PTH / BPL3PTL
    [0x00EC, 0x00EE],   // BPL4PTH / BPL4PTL
    [0x00F0, 0x00F2],   // BPL5PTH / BPL5PTL
    [0x00F4, 0x00F6],   // BPL6PTH / BPL6PTL
];

// ── CodeGen class ─────────────────────────────────────────────────────────────

export class CodeGen {

    /**
     * Generate a complete m68k assembly source from a BASSM AST.
     *
     * @param {object[]} ast  Statement nodes from Parser.parse()
     * @returns {string}      Assembly source text
     * @throws {Error}        If the program has no Graphics statement or uses
     *                        unsupported screen dimensions.
     */
    generate(ast) {
        // ── Locate and validate the Graphics statement ────────────────────────
        const gfxStmt = ast.find(
            s => s && s.type === 'command' && s.name === 'graphics'
        );
        if (!gfxStmt) {
            throw new Error('Every BASSM program must begin with a Graphics statement.');
        }

        const W = this._intArg(gfxStmt, 0, 'Graphics width');
        const H = this._intArg(gfxStmt, 1, 'Graphics height');
        const D = this._intArg(gfxStmt, 2, 'Graphics depth');

        if (W !== 320) {
            throw new Error(`Graphics width ${W} is not supported — only 320 pixels (lores OCS) is implemented.`);
        }
        if (D < 1 || D > 6) {
            throw new Error(`Graphics depth ${D} is out of range — must be 1–6 bitplanes.`);
        }

        // ── Compute display timing constants ──────────────────────────────────
        const colors  = 1 << D;                     // number of colour registers
        const bplcon0 = (D << 12) | 0x0200;         // BPLCON0: depth field + colour enable
        const hStart  = 0x81;                       // horizontal display start (fixed for lores)
        const vStart  = 0x2C;                       // vertical display start  (PAL line 44)
        const diwstrt = (vStart << 8) | hStart;
        const hStop   = (hStart + W) & 0xFF;        // right edge (hardware adds bit 8)
        const vStop   = (vStart + H) & 0xFF;        // bottom edge (hardware adds bit 8)
        const diwstop = (vStop  << 8) | hStop;
        const ddfstrt = 0x003C;                     // fixed for 320-wide lores OCS
        const ddfstop = 0x00D4;

        // ── Build output lines ────────────────────────────────────────────────
        const out = [];

        // Header
        out.push('; ============================================================');
        out.push('; Generated by BASSM — do not edit');
        out.push(`; Screen: ${W}×${H}, ${D} bitplane${D > 1 ? 's' : ''}, ${colors} colours (PAL lores OCS)`);
        out.push('; ============================================================');
        out.push('');

        // EQUs (must precede INCLUDEs so fragment assembly-time expressions resolve)
        out.push(`${pad('GFXWIDTH',12)} EQU ${W}`);
        out.push(`${pad('GFXHEIGHT',12)} EQU ${H}`);
        out.push(`${pad('GFXDEPTH',12)} EQU ${D}`);
        out.push(`${pad('GFXBPR',12)} EQU (GFXWIDTH/8)`);
        out.push(`${pad('GFXPSIZE',12)} EQU (GFXBPR*GFXHEIGHT)`);
        out.push(`${pad('GFXCOLORS',12)} EQU (1<<GFXDEPTH)`);
        out.push(`${pad('GFXBPLCON0',12)} EQU $${hex(bplcon0)}`);
        out.push(`${pad('GFXDIWSTRT',12)} EQU $${hex(diwstrt)}`);
        out.push(`${pad('GFXDIWSTOP',12)} EQU $${hex(diwstop)}`);
        out.push(`${pad('GFXDDFSTRT',12)} EQU $${hex(ddfstrt)}`);
        out.push(`${pad('GFXDDFSTOP',12)} EQU $${hex(ddfstop)}`);
        out.push('');

        // Fragment INCLUDEs (vasm -I must point to fragments dir)
        out.push('        INCLUDE "startup.s"');
        out.push('        INCLUDE "offload.s"');
        out.push('        INCLUDE "graphics.s"');
        out.push('        INCLUDE "cls.s"');
        out.push('        INCLUDE "clscolor.s"');
        out.push('        INCLUDE "color.s"');
        out.push('        INCLUDE "text.s"');
        out.push('');

        // Chip-RAM BSS — bitplane pixel buffers
        out.push('        SECTION gfx_planes,BSS_C');
        out.push('_gfx_planes:    ds.b  GFXPSIZE*GFXDEPTH');
        out.push('');

        // Chip-RAM DATA — copper list template
        out.push('        SECTION gfx_copper,DATA_C');
        out.push('_gfx_copper:');
        out.push(copMove(0x008E, diwstrt, 'DIWSTRT'));
        out.push(copMove(0x0090, diwstop, 'DIWSTOP'));
        out.push(copMove(0x0092, ddfstrt, 'DDFSTRT'));
        out.push(copMove(0x0094, ddfstop, 'DDFSTOP'));
        out.push(copMove(0x0100, bplcon0, 'BPLCON0'));
        out.push(copMove(0x0102, 0x0000,  'BPLCON1 — no scroll'));
        out.push(copMove(0x0104, 0x0000,  'BPLCON2 — default priority'));
        out.push(copMove(0x0108, 0x0000,  'BPL1MOD — no modulo'));
        out.push(copMove(0x010A, 0x0000,  'BPL2MOD'));
        out.push('_gfx_cop_bpl_table:             ; _PatchBitplanePtrs writes here');
        for (let i = 0; i < D; i++) {
            const [pth, ptl] = BPL_PTR_REGS[i];
            out.push(copMove(pth, 0, `BPL${i+1}PTH`));
            out.push(copMove(ptl, 0, `BPL${i+1}PTL`));
        }
        out.push('_gfx_cop_color_table:           ; color.s / cls.s write palette here');
        for (let i = 0; i < colors; i++) {
            const reg = 0x0180 + i * 2;
            out.push(copMove(reg, 0, i === 0 ? 'COLOR00' : null));
        }
        out.push('        dc.w    $FFFF,$FFFE             ; END of copper list');
        out.push('');

        // _setup_graphics subroutine (calls the two helpers from graphics.s)
        out.push('        SECTION gfx_init,CODE');
        out.push('');
        out.push('_setup_graphics:');
        out.push('        lea     _gfx_cop_bpl_table,a0');
        out.push('        lea     _gfx_planes,a1');
        out.push('        moveq   #GFXDEPTH,d0');
        out.push('        move.l  #GFXPSIZE,d1');
        out.push('        bsr     _PatchBitplanePtrs');
        out.push('        lea     _gfx_copper,a0');
        out.push('        bsr     _InstallCopper');
        out.push('        rts');
        out.push('');

        // _main_program — one instruction sequence per Blitz2D statement
        out.push('        SECTION main_code,CODE');
        out.push('');
        out.push('        XDEF    _main_program');
        out.push('_main_program:');

        let strCounter = 0;

        for (const stmt of ast) {
            if (!stmt) continue;
            out.push(...this._genStatement(stmt, () => strCounter++));
        }

        out.push('        rts');
        out.push('');

        return out.join('\n');
    }

    // ── Per-statement code generation ─────────────────────────────────────────

    _genStatement(stmt, nextStrIdx) {
        const lines = [];
        const name  = stmt.name; // already normalised to lowercase by Lexer

        switch (name) {

            case 'graphics':
                // Screen setup — handled at the top level; emit the call here
                lines.push('        bsr     _setup_graphics');
                break;

            case 'cls':
                lines.push('        bsr     _Cls');
                break;

            case 'clscolor': {
                const col = this._intArg(stmt, 0, 'ClsColor');
                lines.push(`        moveq   #${col},d0`);
                lines.push('        bsr     _ClsColor');
                break;
            }

            case 'color': {
                const reg = this._intArg(stmt, 0, 'Color register');
                const r   = this._intArg(stmt, 1, 'Color r') & 0xF;
                const g   = this._intArg(stmt, 2, 'Color g') & 0xF;
                const b   = this._intArg(stmt, 3, 'Color b') & 0xF;
                const rgb = (r << 8) | (g << 4) | b;
                lines.push(`        moveq   #${reg},d0`);
                lines.push(`        move.w  #$${hex(rgb)},d1`);
                lines.push('        bsr     _SetColor');
                break;
            }

            case 'waitvbl':
                lines.push('        bsr     _WaitVBL');
                break;

            case 'text': {
                const x   = this._intArg(stmt, 0, 'Text x');
                const y   = this._intArg(stmt, 1, 'Text y');
                const str = this._strArg(stmt, 2, 'Text string');
                const idx = nextStrIdx();
                const lbl = `.tstr${idx}`;
                const end = `.tpast${idx}`;
                lines.push(`        lea     ${lbl},a0`);
                lines.push(`        move.w  #${x},d0`);
                lines.push(`        move.w  #${y},d1`);
                lines.push('        bsr     _Text');
                lines.push(`        bra.s   ${end}`);
                lines.push(`${lbl}:`);
                lines.push(`        dc.b    "${this._escapeStr(str)}",0`);
                lines.push('        even');
                lines.push(`${end}:`);
                break;
            }

            case 'nprint': {
                const str = this._strArg(stmt, 0, 'NPrint string');
                const idx = nextStrIdx();
                const lbl = `.nstr${idx}`;
                const end = `.npast${idx}`;
                lines.push(`        lea     ${lbl},a0`);
                lines.push('        bsr     _NPrint');
                lines.push(`        bra.s   ${end}`);
                lines.push(`${lbl}:`);
                lines.push(`        dc.b    "${this._escapeStr(str)}",0`);
                lines.push('        even');
                lines.push(`${end}:`);
                break;
            }

            default:
                lines.push(`; [codegen] Unhandled command: ${stmt.name} (line ${stmt.line})`);
                console.warn(`[CodeGen] No code generation for command '${stmt.name}' on line ${stmt.line}`);
        }

        return lines;
    }

    // ── Argument extractors ───────────────────────────────────────────────────

    _intArg(stmt, idx, label) {
        const arg = stmt.args[idx];
        if (!arg || arg.type !== 'int') {
            throw new Error(
                `${label}: expected integer argument at position ${idx} on line ${stmt.line}`
            );
        }
        return arg.value;
    }

    _strArg(stmt, idx, label) {
        const arg = stmt.args[idx];
        if (!arg || arg.type !== 'string') {
            throw new Error(
                `${label}: expected string argument at position ${idx} on line ${stmt.line}`
            );
        }
        return arg.value;
    }

    /** Escape double quotes and backslashes inside a dc.b string */
    _escapeStr(s) {
        return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    }
}
